#!/usr/bin/env node
/* ============================================================
   Builds js/golfers.js, the PGA Tour draft pool: the top golfers by
   official FedEx Cup points for one season, strongest first.

     node tools/golfer-pool.mjs [--season 2026] [--count 80] [--dry-run]

   Reads ESPN directly (no worker): every finished FedEx Cup event's
   leaderboard for names, countries and a first ranking, then each
   leading golfer's official season record for exact points. LIV golfers
   earn no FedEx points, so they never make the list (docs/golf-plan.md:
   no LIV). Run it before a draft, and eyeball the result: a retired or
   injured golfer is worth dropping by hand.
   ============================================================ */
import { writeFileSync } from 'node:fs';
import {
  golfScoreboardUrl, golfLeaderboardUrl, golferRecordUrl,
  parseCalendar, fedexSeasonEvents, parseLeaderboard, condenseLeaderboard, fedexTable, parseGolferRecord
} from '../js/golf.js';

const args = process.argv.slice(2);
const arg = (name, fallback) => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 ? args[i + 1] : fallback;
};
const SEASON = Number(arg('season', new Date().getFullYear()));
const COUNT = Number(arg('count', 80));
const DRY_RUN = args.includes('--dry-run');
const OUT = new URL('../js/golfers.js', import.meta.url);

async function getJson(url){
  const res = await fetch(url);
  if(!res.ok) throw new Error(`${res.status} ${url}`);
  return res.json();
}

const calendar = fedexSeasonEvents(parseCalendar(await getJson(golfScoreboardUrl(SEASON))));
const people = {};
const events = [];
for(const e of calendar){
  if(!e.end || Date.parse(e.end) > Date.now()) continue;
  const lb = await getJson(golfLeaderboardUrl(e.id));
  const condensed = condenseLeaderboard(lb);
  if(condensed.status !== 'post') continue;
  events.push(condensed);
  parseLeaderboard(lb).players.forEach(p => {
    const flag = /countries\/500\/([a-z]+)\.png/.exec(p.flag || '');
    people[p.id] = { name: p.name, country: p.country || '', flag: flag ? flag[1] : '' };
  });
  process.stderr.write('.');
}
process.stderr.write(`\n${events.length} finished events\n`);

// Summed points pick the candidates; official records settle the order.
const candidates = fedexTable(events).filter(r => r.points > 0).slice(0, Math.ceil(COUNT * 1.3));
const ranked = [];
for(const c of candidates){
  let points = c.points;
  try { points = parseGolferRecord(await getJson(golferRecordUrl(c.id, SEASON))).cupPoints || points; } catch (e){}
  ranked.push({ id: c.id, points, ...people[c.id] });
}
ranked.sort((a, b) => b.points - a.points);
const pool = ranked.slice(0, COUNT);

const q = s => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const source = `/* ============================================================
   The PGA Tour draft pool (league key 'pga'): golfers in order of
   official ${SEASON} FedEx Cup points. Generated by tools/golfer-pool.mjs
   on ${new Date().toISOString().slice(0, 10)}; rerun it before a draft, then check the list
   by hand. \`id\` is ESPN's athlete id (headshots, leaderboards, the
   per-golfer record in js/golf.js); \`flag\` is ESPN's country code.
   No LIV golfers: they earn no FedEx points (docs/golf-plan.md).
   ============================================================ */
export const GOLFER_POOL_SEASON = ${SEASON};

export const GOLFERS = [
${pool.map(g => `  { id:${q(g.id)}, name:${q(g.name)}, country:${q(g.country)}, flag:${q(g.flag)}, points:${Math.round(g.points)} }`).join(',\n')}
];
`;
if(DRY_RUN) process.stdout.write(source);
else {
  writeFileSync(OUT, source);
  process.stderr.write(`wrote ${pool.length} golfers to js/golfers.js\n`);
}
